const vocabulary = {
    "Anticipate": "(v) Mong chờ",
    "Antique": "(a) Cổ xưa, lỗi thời",
    "Forehead": "(n) Cái trán",
    "Foremost": "(a) Lỗi lạc nhất",
    "Preoccupy": "(v) Bận tâm, bận trí",
    "Precaution": "(n) Sự đề phòng, sự cảnh cáo",
    "Premature": "(a) Sớm, non, hấp tấp",
    "Postwar": "(a) Thuộc về hậu chiến",
    "Representative": "(n) Đại biểu",
    "Withdraw": "(v) rút lui, rút ra, rút lại",
    "Withhold": "(v) giữ lại, hạn chế, nén, che giấu",
    "Withstand": "(v) chịu đựng",
    "Overcome": "(v) chế ngự, chiến thắng, khắc phục",
    "Overlook": "(v) nhìn từ trên cao, bỏ sót",
    "Overwhelm": "(v) tràn ngập",
    "Overtake": "(v) bắt kịp",
    "Overthrow": "(v) lật đổ", 
    "Superior": "(a) cao hơn, ưu việt hơn",
    "Superb": "(a) nguy nga, hùng vĩ",
    "Superficial": "(a) nông cạn, hời hợt",
    "Sovereign": "(n) vua, quốc vương",
    "The large wave upset the boat": "(v) lật úp", 
    "Up right": "(a, adv) thẳng đứng", 
    "Uphold": "(v) ủng hộ, duy trì, giữ gìn",
};