const vocabulary = {
    "he \"anticipates\" [ˈæn.tɪ.sɪ.peɪts] receiving a gift from his uncle": "(v) mong chờ",
    "she has a fine collection of \"antique\" [ænˈtiːk] furniture": "(a) cổ xưa, lỗi thời",
    "\"forehead\" [ˈfɒr.ɪd]": "(n) cái trán",
    "the \"foremost\" [ˈfɔː.moʊst] painter": "(a) lỗi lạc nhất",
    "we are \"preoccupied\" [priːˈɒk.jʊ.paɪd] with our own affairs": "(v) bận tâm, bận trí",
    "locking doors is a \"precaution\" [prɪˈkɔː.ʃən] against thieves": "(n) sự đề phòng, sự cảnh cáo",
    "a \"premature\" [prɪˈmætʃ.ər] baby": "(a) sớm, non, hấp tấp",
    "the \"postwar\" [ˌpoʊstˈwɔːr] period of economic expansion": "(a) thuộc về hậu chiến",
    "\"representative\" [ˌrɛp.rɪˈzɛn.tə.tɪv]": "(n) đại biểu",
    "\"withdraw\" [wɪðˈdrɔː] money from the account": "(v) rút lui, rút ra, rút lại",
    "you'd better \"withhold\" [wɪðˈhoʊld] your consent for the time being": "(v) giữ lại, hạn chế, nén, che giấu",
    "they cannot \"withstand\" [wɪðˈstænd] the enemy attack": "(v) chịu đựng",
    "he \"overcomes\" [ˌoʊ.vɚˈkʌmz] a strong temptation": "(v) chế ngự, chiến thắng, khắc phục",
    "they build the house to \"overlook\" [ˌoʊ.vɚˈlʊk] the sea": "(v) nhìn từ trên cao, bỏ sót",
    "a great mass of water \"overwhelm\" [ˌoʊ.vɚˈwɛlm] the village": "(v) tràn ngập",
    "I \"overtook\" [ˌoʊ.vɚˈtʊk] him at the traffic lights": "(v) bắt kịp",
    "rebels have \"overthrown\" [ˌoʊ.vɚˈθroʊn] the government": "(v) lật đổ",
    "this pen is \"superior\" [suːˈpɪr.i.ɚ] to that": "(a) cao hơn, ưu việt hơn",
    "a \"superb\" [suːˈpɜːrb] view": "(a) nguy nga, hùng vĩ",
    "he has a \"superficial\" [ˌsuː.pɚˈfɪʃ.əl] knowledge of life": "(a) nông cạn, hời hợt",
    "they selected a prince as a \"sovereign\" [ˈsɒv.ər.ɪn]": "(n) vua, quốc vương",
    "the large wave \"upset\" [ˌʌpˈsɛt] the boat": "(v) lật úp",
    "I cannot stand \"upright\" [ˈʌp.raɪt] anymore": "(a, adv) thẳng đứng",
    "we should \"uphold\" [ʌpˈhoʊld] the good ancient customs our forefathers left behind": "(v) ủng hộ, duy trì, giữ gìn",
    "you look \"depressed\" [dɪˈprɛst] today": "(v) làm chán nản, làm phiền muộn",
    "\"depression\" [dɪˈprɛʃ.ən]": "(n) sự chán nản, sự phiền muộn",
    "the temperature started to \"descend\" [dɪˈsɛnd] rapidly": "(v) tụt xuống",
    "people \"despise\" [dɪˈspaɪz] the slaves": "(v) coi thường, khinh miệt",
    "the new government quickly \"suppressed\" [səˈprɛst] the uprising": "(v) đàn áp",
    "to \"undertake\" [ˌʌn.dɚˈteɪk] that kind of work is to take over a great responsibility": "(v) đảm nhận",
    "he had to \"undergo\" [ˌʌn.dɚˈɡoʊ] a lot of difficulties": "(v) trải qua, chịu đựng",
    "we will take \"underpass\" [ˈʌn.dɚ.pæs] to get across the street": "(n) đường chui",
    "\"inland\" [ˈɪn.lænd] trade": "(a) nội địa",
    "he \"exclaimed\" [ɪkˈskleɪmd] in surprise that he hadn't known about his illness": "(v) kêu lên, la lớn",
    "don't \"expose\" [ɪkˈspoʊz] your skin to the sun": "(v) phơi ra, phô ra",
    "\"exaggerate\" [ɪgˈzædʒ.ə.reɪt]": "(v) phóng đại",
    "\"evaporate\" [ɪˈvæp.ə.reɪt]": "(n) sự bay hơi",
    "\"outskirts\" [ˈaʊt.skɜːrts]": "(n) vùng ngoại ô",
    "the room has a pleasant \"outlook\" [ˈaʊt.lʊk]": "(n) quang cảnh, triển vọng",
    "listening to music is a good \"outlet\" [ˈaʊt.lɛt] for emotions": "(n) phương tiện giải thoát (sức lực, tình cảm)",
    "they \"outnumber\" [ˈaʊtˌnʌm.bɚ] us three to one": "(v) nhiều hơn, đông hơn",
    "she \"outdoes\" [ˌaʊtˈduːz] him in running and swimming": "(v) làm tốt hơn",
    "he has \"outgrown\" [ˌaʊtˈɡroʊn] almost all the clothes he wore last year": "(v) lớn hơn, cao hơn, phát triển nhanh hơn",
    "he \"uttered\" [ˈʌt.ərd] a profound sign": "(v) thốt ra, nói ra",
    "\"utterance\" [ˈʌt.ər.əns]": "(n) sự thốt ra",
    "you're \"utterly\" [ˈʌt.ər.li] mad!": "(adv) hoàn toàn",
    "in the \"utmost\" [ˈʌtmoʊst] danger": "(a) tột bực, cực điểm",
    "we could hardly board the train because there were already so many people \"aboard\" [əˈbɔːrd].": "(adv) trên tàu",
    "after you go \"abroad\" [əˈbrɔːd], you'll have a broader view of life in general": "(adv) ở nước ngoài",
    "Tom and my brother look \"alike\" [əˈlaɪk]": "(a) giống nhau, tương tự",
    "we have to set \"aside\" [əˈsaɪd] some for future": "(adv) về một bên, sang 1 bên",
    "a good sovereign must keep \"abreast\" [əˈbrɛst] with the needs of the people": "(adv) sát cánh, bên cạnh",
    "the family history of his kin is \"akin\" [əˈkɪn] to that mine": "(a) na ná, hơi giống, bà con, thân thuộc",
    "The contract clauses were \"ambiguous\" [æmˈbɪɡjuəs], leading to multiple interpretations": "(a) không rõ ràng",
    "Her essay was \"cohesive\" [koʊˈhiːsɪv], with every part contributing to a central theme": "(a) gắn kết",
    "His \"concise\" [kənˈsaɪs] summary allowed everyone to quickly understand the complex issue": "(a) ngắn gọn",
    "The \"dichotomy\" [daɪˈkɒtəmi] between theory and practice is often challenging for students": "(n) sự phân chia",
    "Flowers are \"ephemeral\" [ɪˈfɛmərəl], yet their beauty is timeless": "(a) ngắn hạn, chóng tàn",
    "The company continues to \"innovate\" [ˈɪnəˌveɪt] to stay ahead in the market": "(v) đổi mới",
    "He is \"meticulous\" [məˈtɪkjʊləs] in his research, paying attention to every small detail": "(a) tỉ mỉ",
    "Understanding the \"nuances\" [ˈnjuːɑːnsɪz] of a foreign language can be challenging": "(n) sắc thái",
    "Social media's \"pervasive\" [pərˈveɪsɪv] influence is evident in our daily lives": "(a) phổ biến, lan rộng",
    "The politician's \"rhetoric\" [ˈrɛtərɪk] was compelling, but lacked substance": "(n) hùng biện",
    "His radical ideas were initially met with \"skepticism\" [ˈskɛptɪˌsɪzəm]": "(n) sự hoài nghi",
    "Her \"tenacious\" [təˈneɪʃəs] pursuit of knowledge inspired her peers": "(a) kiên trì",
    "Mobile phones are \"ubiquitous\" [juːˈbɪkwɪtəs] in modern society": "(a) phổ biến khắp nơi",
    "The stock market is notoriously \"volatile\" [ˈvɒlətaɪl]": "(a) không ổn định, dễ thay đổi",
    "The artist's career reached its \"zenith\" [ˈzɛnɪθ]": "(n) đỉnh cao",
    "The hypothesis was \"plausible\" [ˈplɔːzəbl] but needed more evidence to be confirmed": "(a) hợp lý, có vẻ đúng",
    "His \"arduous\" [ˈɑːrdʒuəs] journey across the desert was both challenging and rewarding": "(a) gian khổ, khó khăn",
    "She has an \"innate\" [ɪˈneɪt] talent for music that is truly remarkable": "(a) bẩm sinh",
    "The novel's plot was \"convoluted\" [ˈkɒnvəluːtɪd], making it difficult to follow": "(a) phức tạp, rắc rối",
    "The CEO's \"pragmatic\" [prægˈmætɪk] approach to business led to impressive results": "(a) thực dụng, thực tế",
    "His \"astute\" [əˈstjuːt] observations were crucial in solving the problem": "(a) sắc sảo, nhạy bén",
    "She expressed her ideas with \"eloquence\" [ˈɛləkwəns], captivating the audience": "(n) hùng biện, lưu loát",
    "The \"anomaly\" [əˈnɒməli] in the data prompted further investigation": "(n) dị thường, không bình thường",
    "He showed \"resilience\" [rɪˈzɪliəns] in the face of adversity": "(n) sự kiên cường, phục hồi nhanh",
    "The \"aesthetic\" [iːsˈθetɪk] appeal of the artwork was undeniable": "(a) thuộc về mỹ cảm, thẩm mỹ",
    "The \"nostalgia\" [nɒˈstældʒə] for his childhood days was evident in his stories": "(n) hoài niệm",
    "Her \"empathy\" [ˈɛmpəθi] towards others made her a great friend": "(n) sự đồng cảm, thấu hiểu",
    "The lawyer's argument was \"succinct\" [səkˈsɪŋkt] and to the point": "(a) ngắn gọn, xúc tích",
    "The company's \"autonomy\" [ɔːˈtɒnəmi] in decision-making was reduced after the merger": "(n) sự tự trị, tự quản",
    "The \"enigma\" [ɪˈnɪɡmə] of the ancient ruins fascinated the archaeologists": "(n) điều bí ẩn, khó hiểu",
    "The \"altruism\" [ˈæl.tru.ɪ.zəm] of the volunteers was commendable": "(n) lòng vị tha, lòng nhân ái",
    "She spoke with \"eloquence\" [ˈɛl.ə.kwəns] about her experiences": "(n) khả năng diễn đạt trôi chảy",
    "The \"paradox\" [ˈpær.ə.dɒks] of thrift suggests saving can be harmful to the economy": "(n) nghịch lý",
    "A \"plethora\" [ˈplɛθ.ə.rə] of options can sometimes be overwhelming": "(n) sự thừa thãi",
    "The \"quandary\" [ˈkwɒn.də.ri] of choosing the right path was evident": "(n) tình huống khó xử",
    "His \"resilience\" [rɪˈzɪl.jəns] in the face of adversity is inspiring": "(n) khả năng phục hồi nhanh chóng",
    "The \"ambivalence\" [æmˈbɪv.ə.ləns] in her decision was clear": "(n) lòng lưỡng lự",
    "A \"catalyst\" [ˈkæt.ə.lɪst] for change is often necessary in stagnant situations": "(n) chất xúc tác",
    "The discussion had a \"cerebral\" [ˈsɛr.ɪ.brəl] nature": "(a) thuộc về trí óc, trí tuệ",
    "He had an \"ephemeral\" [ɪˈfɛm.ə.rəl] interest in painting": "(a) ngắn hạn, chóng tàn",
    "Their \"juxtaposition\" [ˌdʒʌk.stə.pəˈzɪʃ.ən] highlighted the contrast": "(n) sự đặt cạnh nhau",
    "The \"nuance\" [ˈnjuː.ɑːns] of her expression was difficult to catch": "(n) sắc thái nhỏ",
    "He demonstrated great \"tenacity\" [tɪˈnæs.ɪ.ti] in solving the problem": "(n) sự kiên trì, bền bỉ",
    "The project requires \"meticulous\" [mɪˈtɪk.jʊ.ləs] planning": "(a) tỉ mỉ, kỹ lưỡng",
    "Her \"insidious\" [ɪnˈsɪd.i.əs] plan slowly undermined his confidence": "(a) quỷ quyệt, xảo quyệt",
    "The \"ubiquitous\" [juːˈbɪk.wɪ.təs] use of smartphones is noticeable": "(a) phổ biến khắp nơi",
    "His \"rhetoric\" [ˈrɛt.ə.rɪk] was powerful but sometimes misleading": "(n) hùng biện, lời lẽ hoa mỹ",
    "The \"idiosyncrasy\" [ˌɪd.i.əˈsɪŋ.krə.si] of his behavior was well-known": "(n) đặc điểm, tính cách riêng",
    "Her \"intuition\" [ˌɪn.tuˈɪʃ.ən] about people was rarely wrong": "(n) trực giác",
    "The \"conundrum\" [kəˈnʌn.drəm] of the missing files remained unsolved": "(n) câu đố khó giải",
};