const vocabulary = {
    "anticipate": "(v) Mong chờ",
    "antique": "(a) Cổ xưa, lỗi thời",
    "forehead": "(n) Cái trán",
    "foremost": "(a) Lỗi lạc nhất",
    "preoccupy": "(v) Bận tâm, bận trí",
    "precaution": "(n) Sự đề phòng, sự cảnh cáo",
    "premature": "(a) Sớm, non, hấp tấp",
    "postwar": "(a) Thuộc về hậu chiến",
    "representative": "(n) Đại biểu",
    "withdraw": "(v) rút lui, rút ra, rút lại",
    "withhold": "(v) giữ lại, hạn chế, nén, che giấu",
    "withstand": "(v) chịu đựng",
    "overcome": "(v) chế ngự, chiến thắng, khắc phục",
    "overlook": "(v) nhìn từ trên cao, bỏ sót",
    "overwhelm": "(v) tràn ngập",
    "overtake": "(v) bắt kịp",
    "overthrow": "(v) lật đổ", 
    "superior": "(a) cao hơn, ưu việt hơn",
    "superb": "(a) nguy nga, hùng vĩ",
    "superficial": "(a) nông cạn, hời hợt",
    "sovereign": "(n) vua, quốc vương",
    "the large wave upset the boat": "(v) lật úp", 
    "up right": "(a, adv) thẳng đứng", 
    "uphold": "(v) ủng hộ, duy trì, giữ gìn",
    "depress": "(v) làm chán nản, làm phiền muộn",
    "depression": "(n) sụ chán nản, sụ phiền muộn",
    "descend": "(v) tụt xuống",
    "despise": "(v) coi thường, khinh miệt",
    "suppress": "(v) đàn áp", 
    "undertake": "(v) đảm nhận",
    "undergo": "(v) trải qua, chịu đựng",
    "underpass": "(n) đường chui",
    "inland":"(a) nội địa",
    "exclaim": "(v) kêu lên, la lớn",
    "expose": "(v) phơi ra, phô ra",
    "exaggerate": "(v) phóng đại",
    "evaporate": "(n) sự bay hơi",
    "outskirts": "(n) vùng ngoại ô",
    "outlook": "(n) quang cảnh, triển vọng",
    "outlet": "(n) phương tiện giải thoát (sức lực, tình cảm)",
    "they \"outnumnber\" us three to one": "(v) nhiều hơn, đông hơn",
    "she \"outdoes\" him in running and swimming": "(v) làm tốt hơn",
    "he has outgrown almost all the clothes he wore last year": "(v) lớn hơn, cao hơn, phát triển nhanh hơn",
    "utter": "(v) thốt ra, nói ra",
    "utterance": "(n) sự thốt ra",
    "utmost": "(a) tột bực, cực điểm",
};